spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      location: D:/uploadFiles
      max-file-size: 200MB
      max-request-size: 215MB

  file:
    uploadDir: D:/uploadFiles/
  cache:
    type: ehcache
    jcache:
      config: classpath:encache.xml

  datasource:
    url: jdbc:h2:mem:wishwordrobe
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      default_batch_fetch_size: 1000
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    activate:
      on-profile: oracle

    datasource:
     url: jdbc:oracle:thin:@localhost:1521:orcl
     username: wish
     password: a123
     driver-class-name: oracle.jdbc.OracleDriver

    jpa:
     hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.Oracle19cDialect

    data:
      mongodb:
        uri: mongodb://localhost:27017/wishwordrobe




  profiles:
    active: dev



  redis:
    host: localhost
    port: 6379


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  issuer: wishful@gmail.com
  secret_key: iwish

weather:
  api:
    apiKey: "dJ+1bX3L4D5nk3DlGR7hHcEexw5lZK9kOiQYE3SUIEmLH7O/Hd/7TBDEWzgPvqQJbYyWJpgLjR67KsK59dX3ow=="
    baseUrl: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
    villageFcstUrl: "/getVilageFcst"
    ultraSrtFcstUrl: "/getUltraSrtFcst"
    ultraSrtNcstUrl: "/getUltraSrtNcst"
app:
  webpush:
    public-key: BP4LfGdxmHwrq-rKtbXnIhtX89V68HGH1BM96mlWWdimEj5M7_ow5gZ6zkbulDJaTdb7lzyCpi35RJJwVl819gI
    private-key: u3oOxm0mJ_fatc9nLIPupVOQCrMK4uVEH7VJ8cprKpE

wish:
  local:
    file:
      base:
        directory: "C:/Users/gyeongryun"


