spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/wishwardrobe
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      default_batch_fetch_size: 1000
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  issuer: wishful@gmail.com
  secret_key: iwish